### PR TITLE
Added icon left

### PR DESCRIPTION
**Pull request by lewis-munyi**
Added option to position icon on the left

### CODE REVIEW

**Comment by lewis-munyi** [comment]
Thank you for this project. @Daniel-Knights

**Comment by Daniel-Knights** [comment]
Hi, @lewis-munyi. Appreciate your contribution! I've merged it and made a few alterations.

**Comment by lewis-munyi** [comment]
> Hi, @lewis-munyi. Appreciate your contribution! I've merged it and made a few alterations.

Great! Please update the npm package so I can get the changes for a project I'm working on.

**Comment by Daniel-Knights** [comment]
Should be up and usable already 👍

**Pull request merged**
